name: kan
version: "1.33"
license: "GPL-2.0-or-later"
date: 2021-11-15
description: |
    including double coset rewriting systems

authors:
    - name: Anne Heyworth
    - name: Chris Wensley
      url: https://github.com/gap-packages/kan

maintainers:
    - name: Chris Wensley
      url: https://github.com/gap-packages/kan

GAP: ">=4.11.0"

needed-pkgs:
    - name: "automata"
      version: ">= 1.14"
      url: "https://gap-packages.github.io/automata/"
    - name: "GAPDoc"
      version: ">= 1.6.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "kbmag"
      version: ">= 1.5.8"
      url: "https://gap-packages.github.io/kbmag"

www: https://gap-packages.github.io/kan/
readme: README.md
packageinfo: https://gap-packages.github.io/kan/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/kan/releases/download/v1.33/kan-1.33.tar.gz

abstract: |
    The Kan package provides functions for the computation of normal forms   of representatives of double cosets of finitely presented groups.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Kan extension, double coset rewriting system, induced action.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HW21</span>]   <b class='BibAuthor'>Heyworth, A. and Wensley, C.</b>,
     <i class='BibTitle'>kan, including double coset rewriting systems,
             Version 1.33</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/kan/">https://gap-packages.github.io/kan/</a></span>.
    </p>
    

bibtex: |
    @misc{ kan1.33,
      author =           {Heyworth, A. and Wensley, C.},
      title =            {{kan},   including  double  coset  rewriting  systems,
                          {V}ersion 1.33},
      month =            {Nov},
      year =             {2021},
      note =             {Refereed GAP package},
      howpublished =     {\href            {https://gap-packages.github.io/kan/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{kan/}}},
      keywords =         {Kan  extension; double coset rewriting system; induced
                          action},
      printedkey =       {HW21}
    }

